### ISSUE TITLE
Ponce standard instructions not supported windbg

### ISSUE THREAD

**Issue by JJK96** [illera88/Ponce#137]
I'm using windbg kernel debugger in IDA. Then I enable Ponce tracing in taint mode.

I get a lot of messages like the following:

```
[!] Instruction at 0xfffff80053e0cbb2 not supported by Triton: call 0xfffff80053e0d260 (Thread id: 2)
[!] Instruction at 0xfffff80053e0d260 not supported by Triton: mov qword ptr [rsp + 8], rbx (Thread id: 2)
[!] Instruction at 0xfffff80053e0d265 not supported by Triton: mov qword ptr [rsp + 0x10], rsi (Thread id: 2)
[!] Instruction at 0xfffff80053e0d26a not supported by Triton: push rdi (Thread id: 2)
[!] Instruction at 0xfffff80053e0d26b not supported by Triton: push r12 (Thread id: 2)
[!] Instruction at 0xfffff80053e0d26d not supported by Triton: push r13 (Thread id: 2)
[!] Instruction at 0xfffff80053e0d26f not supported by Triton: push r14 (Thread id: 2)
```

It seems that all instructions that Triton encounters are not supported.
Does anyone know what is going wrong here?

**Comment by illera88** [comment]
Hey @JJK96 ,

Thank you for bringing this up. I did some changes in that part of the code last time I poked with it. I tested it manually with some of the tests programs and worked fine for me. Not sure what it may be happening. 

I should write some tests to prevent this from happen in the future and make Ponce more robust. A lot of parts are difficult to test since are UI with integration with IDA but the triton related stuff should be testable. 

I won't be able to look into it in the next couple of weeks. @0ca can you please take a look at this?

Cheers

**Comment by illera88** [comment]
It may be also related to https://github.com/JonathanSalwan/Triton/issues/1252

**Comment by 0ca** [comment]
I'm getting the same error using IDA 7.6 in Windows with the local debugger.
```
[!] Instruction at 0x7ff74a8f107b not supported by Triton: call 0x7ff74a8f1010 (Thread id: 4968)
[!] Instruction at 0x7ff74a8f1080 not supported by Triton: xor eax, eax (Thread id: 4968)
```
I'm going to take a look

**Comment by 0ca** [comment]
The release 0.3.6 was using the new Triton library with an old commit from last year,

The latest release fixes it: https://github.com/illera88/Ponce/releases/tag/v0.3.7
