### ISSUE TITLE
About Float Point Instructions

### ISSUE THREAD

**Issue by pfsun** [illera88/Ponce#59]
I just try one float-point computing code. Some float-point instruction are missing.
![image](https://cloud.githubusercontent.com/assets/4397561/19287726/eea43e7c-8fd0-11e6-859a-1b3d7ce208fd.png)

@0ca @illera88 Will you try to add more float point instructions support or other solutions? I also saw some words about float point instructions in Triton website ([5.1 - Few words about floating-point instructions](http://triton.quarkslab.com/blog/What-kind-of-semantics-information-Triton-can-provide/#5.1)) .

**Comment by 0ca** [comment]
It looks it is a Triton issue, as you can see Triton is not generating symbolic expressions for those instructions.

So we can't check if they are symbolic or not :(

We hope in the future the Triton support for floating instructions will be better.

**Comment by pfsun** [comment]
Yes. It is a Triton issue. It looks they will not support recently :( Thanks.

**Comment by 0ca** [comment]
We should show some warnings when Ponce finds unsupported instructions so the user can know without use the "Add comments with symbolic expression" if an instruction is supported.

**Comment by JonathanSalwan** [comment]
> It looks it is a Triton issue, as you can see Triton is not generating symbolic expressions for those instructions.

Right. [Here](http://triton.quarkslab.com/documentation/doxygen/SMT_Semantics_Supported_page.html) is our list of supported instructions. The problem with floating point is that SMT solvers cannot deal with expressions which contain both theories bit-vector and floating-point. This behavior is a real problem for us due to the SSA-form. Example:

```
mov [mem], rax    ; rax comes from bitvector theory
movq xmm1, [mem]  ; generic
addps xmm2, xmm1  ; computation based on floating point theory (where xmm1 comes from bv)
```

@0ca, regarding [#400](https://github.com/JonathanSalwan/Triton/issues/400), I will return a boolean value to let you catch unsupported instructions.

Cheers,

**Comment by 0ca** [comment]
Done, thank you for the help!
https://github.com/illera88/Ponce/commit/eff1ed4158207cdd0349dce77c50639a5613b51c
