### ISSUE TITLE
IDA 7.0 build

### ISSUE THREAD

**Issue by emc2314** [illera88/Ponce#77]
Please add IDA 7.0 builds.

**Comment by sunnyelf** [comment]
+1

**Comment by illera88** [comment]
We'll try to do so in the next few weeks.

**Comment by vanhauser-thc** [comment]
Hey guys what is the status for IDA 7.0 support/builds?
thanks!

**Comment by illera88** [comment]
Sorry but some shit presented at work now and we can't put time on this. It's in our To Do list but it will have to wait at least one more month :(

**Comment by mxmssh** [comment]
I am starting working on this problem.

**Comment by mxmssh** [comment]
IDA's team introduces a lot of changes for API https://www.hex-rays.com/products/ida/7.0/docs/api70_porting_guide.shtml in IDA 7. The most important one for us is that IDA is a 64-bit application now.

To be able to port Ponce for IDA 7, we have to do the following:

1) Replace, old APIs with new ones where it is necessary (done).
2) Since IDA is a native 64-bit application, plugins should also be written as a native 64-bit applications. Thus, we need to recompile all our external libs (triton, z3, bootstone), since they are all 32-bit and rewrite Ponce to be 64-bit itself. 
3) There is a significant change in choose() display, we have to create a new class derived from 'chooser_t'.

**Comment by wootski** [comment]
Are all of these changes in master? What else is required to finalise support for 7.0? It looks like there a few different issues with comments on IDA 7 support.

**Comment by mxmssh** [comment]
Yes, all of these changes are in master. What is required now is a comprehensive testing and fixing potentual issues exist in Ponce in IDA 7.

**Comment by LusKrew** [comment]
Its been 4 years and Im still waiting

**Comment by illera88** [comment]
https://github.com/illera88/Ponce/actions/runs/115490440
